config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events do 
    member do
      post "rsvp"
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  resources :users, only: [:show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root "events#index"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User", foreign_key: "creator_id"
    has_many :attendances, dependent: :destroy
    has_many :attendees, through: :attendances, source: :user

    scope :past, -> { where("event_date < ?", Date.today) }
    scope :upcoming, -> { where("event_date >= ?", Date.today) }
    scope :undated, -> { where(event_date: nil) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :hosted_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def new
        @event = Event.new
    end

    def create
        @event = current_user.hosted_events.build(event_params)
    
        if @event.save
          redirect_to events_path
        else
          puts event_params
          render :new, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    def index
        @events = Event.all
        @past_events = Event.past
        @upcoming_events = Event.upcoming
        @undated_events = Event.undated
    end
    
    def rsvp
        @event = Event.find(params[:id])
        if @event.attendees.include?(current_user)
            flash[:alert] = "You are going to this event"
        else
            if current_user.attended_events << @event
                flash[:notice] = "You have successfully RSVPed to the event."
            else
                flash[:alert] = "There was an error RSVPing to the event."
            end
        end
        
        redirect_to events_path
    end

    private

    def event_params
        params.require(:event).permit(:event_name, :location, :event_date, :details)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user_events = current_user.hosted_events
        @current_date = Date.today
        @future_events = current_user.attended_events.where('event_date >= ?', @current_date)
        @past_events = current_user.attended_events.where('event_date < ?', @current_date)
        @undated_events = current_user.attended_events.where(event_date: nil)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
    <div>
        <%= form.label :event_name %><br>
        <%= form.text_field :event_name %>
        <% post.errors.full_messages_for(:event_name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :location %><br>
        <%= form.text_area :location %>
        <% post.errors.full_messages_for(:location).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :event_date %><br>
        <%= form.text_area :event_date %>
        <% post.errors.full_messages_for(:event_date).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :details %><br>
        <%= form.text_area :details %>
        <% post.errors.full_messages_for(:details).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<% @upcoming_events.each do |event| %>
  <div class="event">
    <h2><%= event.event_name %></h2>
    <p><%= event.location %></p>
    <p><%= event.event_date %></p>
    <% unless event.attendees.include?(current_user) %>
      <%= button_to 'RSVP', rsvp_event_path(event), method: :post, class: "btn btn-primary" %>
    <% else %>
      <p>You are going to this event.</p>
    <% end %>
    <%= button_to "View Details", event_path(event.id), method: :get %>
  </div>
<% end %>

<h1> Past Events </h1>

<% @past_events.each do |event| %>
  <div class="event">
    <h2><%= event.event_name %></h2>
    <p><%= event.location %></p>
    <p><%= event.event_date %></p>
    <%= button_to "View Details", event_path(event.id), method: :get %>
  </div>
<% end %>

<h1> Undated Events </h1>

<% @undated_events.each do |event| %>
  <div class="event">
    <h2><%= event.event_name %></h2>
    <p><%= event.location %></p>
    <p><%= event.event_date %></p>
    <% unless event.attendees.include?(current_user) %>
      <%= button_to 'RSVP', rsvp_event_path(event), method: :post, class: "btn btn-primary" %>
    <% else %>
      <p>You are going to this event.</p>
    <% end %>
    <%= button_to "View Details", event_path(event.id), method: :get %>
  </div>
<% end %>

app/views/events/new.html.erb
<%= render "form", post: @event %>

app/views/events/show.html.erb
<h1><%= @event.event_name %></h1>

<p><strong>Date:</strong> <%= @event.event_date %></p>
<p><strong>Location:</strong> <%= @event.location %></p>
<p><strong>Description:</strong> <%= @event.details %></p>

<h2>Attendees:</h2>
<% @event.attendees.each do |attendee| %>
    <p><%= attendee.email %></p>
<% end %>

<h3>Creator: <%= @event.creator.email %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
        <nav>
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'New Event', new_event_path %></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Your Events', user_path(current_user) %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Your Hosted Events</h1>

<% @user_events.each do |user_event| %>
    <div class="user_event">
      <h2><%= user_event.event_name %></h2>
      <p><%= user_event.location %></p>
      <p><%= user_event.event_date %></p>
    </div>
<% end %>

<h1>Upcoming Events</h1>

<% @future_events.each do |attended_event| %>
  <div class="attended_event">
    <h2><%= attended_event.event_name %></h2>
    <p><%= attended_event.location %></p>
    <p><%= attended_event.event_date %></p>
  </div>
<% end %>

<h1>Past Events</h1>

<% @past_events.each do |attended_event| %>
  <div class="attended_event">
    <h2><%= attended_event.event_name %></h2>
    <p><%= attended_event.location %></p>
    <p><%= attended_event.event_date %></p>
  </div>
<% end %>

<h1>Undated Events</h1>

<% @undated_events.each do |attended_event| %>
  <div class="attended_event">
    <h2><%= attended_event.event_name %></h2>
    <p><%= attended_event.location %></p>
    <p><%= attended_event.event_date %></p>
  </div>
<% end %>